### ISSUE TITLE
Calculation error in country scientific production

### ISSUE THREAD

**Issue by PedroSennaVieira** [massimoaria/bibliometrix#133]
Hello Massimo, I'm a big fan of the package, however, I detected an error of calculation, 

I did a research that found 105 papers (confirmed by bibliometrix) and then, the total of publications in Country scientific production is 150 (the summation). I Believe I know why is this happening:

1 - When I hit Ctrl + F and look for "United States" it shows me 42 entries, which is exactly that the country scientific production is showing
2  I detected that United states are being counted in both C1 and RP fields:
![image](https://user-images.githubusercontent.com/51272424/90316697-3de79980-defa-11ea-88b0-8ae8ce9614b9.png)

**Comment by massimoaria** [comment]
It's not a calculation error.
For each country, Country Scientific Production measures the number of co-authors affiliated to that specific country. 
This means that if in a paper there are two USA authors, the USA's Country Scientific Production will increase of two.

PS. You should not check your data using ctrl+F because for seak of simplicity only the first 150 characters are printed.
The best way is to export your data as an excel file (using the SAVE button in the Data menu) and looking at using Excel.
