### ISSUE TITLE
Error in AU1_CO extraction

### ISSUE THREAD

**Issue by yuyllove** [massimoaria/bibliometrix#184]
Aria,
     This is a nice work!
     When I got the countris of the corresponding authors using biblioAnalysis function, some errors occurred.  For example, The RP is "SANTOS-HERMOSA, G (CORRESPONDING AUTHOR), UNIV BARCELONA, FAC INFORMACIO & MITJANS AUDIOVISUALS, MELCIOR DE PALAU 140, BARCELONA 08014, SPAIN." The results is "**PALAU**", not "**SPAIN**". I considered that something wrong was happend in metaTagExtraction function.  I doubt the same error occurr in AU_CO. 
     Thank you.

**Comment by Pengustc** [comment]
I checked the source code and found that the country/region names are extracted based on the regular expression, rather than split  the C1 addresses directly. Maybe the mistake came from here. 
BY: Palau, officially the Republic of Palau and historically Belau, Palaos or Pelew, is an island country in the western Pacific.
