### ISSUE TITLE
Older version of Bibliometrix?

### ISSUE THREAD

**Issue by gilienv** [massimoaria/bibliometrix#188]
I just noted a lovely Hist plot in the tutorial section of documentation dated July 2018:
[https://bibliometrix.org/documents/bibliometrix_Report.html]:
However, 
Using the exact SAME code:
net <- histPlot(histResults, n=20, size.cex=TRUE, size = 5, labelsize = 3, arrowsize = 0.5)
on my data returns an error:

Error in histPlot(histResults, n = 20, size.cex = TRUE, size = 5, labelsize = 3,  : 
  unused arguments (size.cex = TRUE, arrowsize = 0.5)

Removing these two arguments returns a plot that looks nothing like what the documentation showed.. I am particulary interested in the same thick pastel curved edges and arrows!

My view is that this plot was being made by the older version of the package and maybe the new package has updates that don't have the same parameters etc,
I'm willing to resolve this by installing an older version of the package on an older version of R..whatever may get the code to work!

Any help will be greatly apreciated!

-Gita

**Comment by massimoaria** [comment]
> I just noted a lovely Hist plot in the tutorial section of documentation dated July 2018:
> [https://bibliometrix.org/documents/bibliometrix_Report.html]:
> However,
> Using the exact SAME code:
> net <- histPlot(histResults, n=20, size.cex=TRUE, size = 5, labelsize = 3, arrowsize = 0.5)
> on my data returns an error:
> 
> Error in histPlot(histResults, n = 20, size.cex = TRUE, size = 5, labelsize = 3, :
> unused arguments (size.cex = TRUE, arrowsize = 0.5)
> 
> Removing these two arguments returns a plot that looks nothing like what the documentation showed. I am particulary interested in the same thick pastel curved edges and arrows!
> 
> My view is that this plot was being made by the older version of the package and maybe the new package has updates that don't have the same parameters etc,
> I'm willing to resolve this by installing an older version of the package on an older version of R..whatever may get the code to work!
> 
> Any help will be greatly apreciated!
> 
> -Gita

You can install a previous version of Bibliometrix by downloading the source from the CRAN archive: 
https://cran.r-project.org/src/contrib/Archive/bibliometrix/

We changed the plot because we decided that the use of a random color for each edge was not the best choice to identify different clusters. Moreover, the package ggraph, that we used in the previous version to build up the historiograph, is not supported by plotly environment. So when we decided to convert all plots in dynamic graphs for the biblioshiny interface, we decided to switch to ggnetwork to produce the new plot.


https://www.bibliometrix.org/vignettes/Introduction_to_bibliometrix.html

**Comment by gilienv** [comment]
Thank you so much! This is very helpful :)
