### ISSUE TITLE
New WoS - limited output options

### ISSUE THREAD

**Issue by ChrisHarrod** [massimoaria/bibliometrix#217]
Folks
with the update to WoS, it seems that when exporting records to a plain text file that is is only possible to export Author, Title, Source and Abstract. Clearly this is not enough to provide relevant information to Bibliometrix. 

old format:

![image](https://user-images.githubusercontent.com/10197300/135701910-dc70fd76-74bd-4268-aab9-da5c63591b11.png)

new format:

![image](https://user-images.githubusercontent.com/10197300/135701894-bfc5ad64-490e-4206-896c-c999229e1485.png)

For now the user can use the 'classic' interface for WoS, but it might be worth updating your tutorial page (or if it is actually possible in the new version, pointing the user to how it can be done). 

Cheers and thanks for a great piece of software

**Comment by massimoaria** [comment]
The limitation was due to a bug in the new WoS interface.
They have already solved the issue.
Now it is possible to download the complete set of metadata by selecting "Full Record and Cited References" in the Record Content field:

![image](https://user-images.githubusercontent.com/16023543/135992584-436bf737-9a1b-4a12-8c5b-e68e7e4d61e1.png)

**Comment by ChrisHarrod** [comment]
Brilliant! Many thanks for a great piece of software.
Chris
