### ISSUE TITLE
Error Scielo

### ISSUE THREAD

**Issue by Smolski** [massimoaria/bibliometrix#22]
I cant import data from Scielo. The error: Error in seq.default(iStart, iStop) : 'from' must be a finite number.

Loading txt or bib files into R environment
D <- readFiles("D:/Educ/novaeconomia.txt")

Converting the loaded files into a R bibliographic dataframe
M <- convert2df(D, dbsource="isi",format="plaintext")

How can I solve?
Thanks
[novaeconomia.txt](https://github.com/massimoaria/bibliometrix/files/2636541/novaeconomia.txt)

**Comment by massimoaria** [comment]
convert2df doesn't work because your txt file format is not in the WOS's plaintext format.
WOS uses space characters and not tabultate one (as in your file).
Please take a look to the example file (downloaded from WOS) I attached here.
[savedrecs.txt](https://github.com/massimoaria/bibliometrix/files/2636908/savedrecs.txt)

**Comment by rbali** [comment]
I was having the same issue with Scielo. Trying different alternatives I found the solution. Instead of getting plaintext or bibtex files, export to "Endnote para Desktop" that creates a `savedrecs.ciw` file.
That file is read without issues

```
D <- readFiles("savedrecs.ciw")
M <- convert2df(D, dbsource="wos",format="plaintext")
```
