### ISSUE TITLE
Error in `.rowNamesDF<-`(x, value = value) :    duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by gaiobr** [massimoaria/bibliometrix#241]
Dear all,

I'm trying to use:
`suppressWarnings(
CS <- conceptualStructure(M, method="MCA", field="AB", minDegree=5, clust=5, stemming=FALSE, labelsize=15,documents=20)
)`

But this returns:

Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed

In my dataset I had two occurrences that are different articles, but have the same first author, the same journal and the same year. But, they are not duplicated, since are different publications (i.e., titles and abstracts). 

[test.csv](https://github.com/massimoaria/bibliometrix/files/8412056/test.csv)

Would you please help me?

**Comment by massimoaria** [comment]
Your file works fine on my pc.

I used this code:

`
M <- convert2df("test.csv", "scopus","csv")
`
Converting your scopus collection into a bibliographic dataframe

Done!

Generating affiliation field tag AU_UN from C1:  Done!

`
CS <- conceptualStructure(M, method="MCA", field="AB", minDegree=5, clust=4, stemming=FALSE, labelsize=15,documents=20)
`

The problem is that you have only 14 articles with an abstract and setting the minimum word frequency to 5, the function returns only 4 clusters, each of which consists of a single word! 

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/16023543/161702568-5eba770f-f85b-46bc-a6a4-9c5be908003d.png">

**Comment by gaiobr** [comment]
Thank you! Your suggestion solves my problem.  

Despite the solution, I will add some information. 

My data is from the Web of Science. I'm using a data frame that was generated by several .bib files: 
1. I converted each .bib (WoS) file using convert2df()
2. I merged each data frame into a unique data frame and manually edited 
3. I made some changes (added some columns) 
4. I saved as .rds 
5. I tried using conceptualStructure() and got the above error 

So when I saw your suggestion, I saved my .rds file as .csv and read the .csv using convert2df() and the "scopus" option despite the original source being WoS.

Hope this doesn't interfere with anything in the analysis
