### ISSUE TITLE
Coupling analysis results change randomly

### ISSUE THREAD

**Issue by Xavi-GitHub** [massimoaria/bibliometrix#259]
Hello
Either using R Studio or Biblioshiny, every time I repeat the “run” command (R Studio), our the “Apply” button (Biblioshiny), without changing anything (keeping the exact same arguments), the returned coupling map and bibliometric results are different. I get no errors, but the results seem to change randomly.
Why is this? How these results can be valid for analysis and interpretation?
Thank you
Xavi

**Comment by massimoaria** [comment]
Unfortunately, this happens because igraph team changed the "louvain" algorithm that now returns different results at each iteration. You can take a look at this discussion for more info https://github.com/igraph/rigraph/issues/539

To overcome the issue, we decided to change the default community detection algorithm and now it is set as "walktrap".
Moreover, we also added the argument "cluster" to the function couplingMap() so a user can choose the community detection algorithm that he prefers.
The same we did for all methods based on the network analysis (thematicMap, thematicEvolution, etc.)
