### ISSUE TITLE
Dimension CSV file not getting converted to dataframe

### ISSUE THREAD

**Issue by kawai-grammer** [massimoaria/bibliometrix#262]
Hi, 
I have downloaded a csv data file from dimensions and it shows an error which I can't decipher. Please anyone help.

OUPUT is something like:
Converting your dimensions collection into a bibliographic dataframe

Rows: 49 Columns: 15                                                                                           
-- Column specification ----------------------------------------------------
Delimiter: ","
chr (11): pub.1147772711, 10.1007/s11356-022-20132-1, IoT technologies i...
dbl  (4): 2022, 29, 32, 0

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.

Error in `$<-.data.frame`(`*tmp*`, "AU", value = character(0)) : 
  replacement has 0 rows, data has 49
In addition: Warning message:
One or more parsing issues, see `problems()` for details
The file I used is :
[vos.csv](https://github.com/massimoaria/bibliometrix/files/9156189/vos.csv)
I used another csv file for testing, which also gives out same error
[new_db.csv](https://github.com/massimoaria/bibliometrix/files/9156200/new_db.csv)
:

**Comment by massimoaria** [comment]
Hi, 
it doesn't work because probably you removed the first line into the csv file.
typically the line contains information about the download such as:
"About the data: Exported on ......, ect."
 
You do not need to do that. The importing function does it automatically.
The typical Dimensions csv file start as:
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/16023543/183241361-eac8536b-8e1c-46b6-b410-9ee6dd6a46f0.png">
