### ISSUE TITLE
Error when using "normalize" arguement in networkPlot()

### ISSUE THREAD

**Issue by evrimyanar** [massimoaria/bibliometrix#300]
Hello, 

I am conducting a co-citation analysis on biblioshiny. After the update, I noticed that there is no normalization option while creating the network. Therefore, I tried creating the co-citation network on R. However, as soon as I include the normalize argument in the networkPlot() function, I receive an error. Without the normalize argument, the plot is produced without a problem. 

>   networkPlot(Cocitematrix, n = 50, normalize = "association", type = "auto", cluster = "Louvain")
Error: vector memory exhausted (limit reached?)

I would really appreciate for any help/suggestion. 

Kind regards,

Evrim Yanar

**Comment by massimoaria** [comment]
Usually, the cocitation analysis results in a cocitation matrix of enormous size. In this case, when performing normalization calculations, R fails to store the matrix in memory because it is too large.
Try setting a different memory limit in R or use a computer with more ram memory.

We are working on a more efficient implementation of these matrices so as to overcome the problem.

**Comment by evrimyanar** [comment]
Thank you for the response!
