### ISSUE TITLE
Error when two or more authors share the last name and first letter of the first name in relevant authors section

### ISSUE THREAD

**Issue by a45285** [massimoaria/bibliometrix#331]
Hello, everyone

I’ve been using bibliometrix/biblioshiny for a while now and it is a valuable and useful tool! Kudos to all!!!

However, I just realized that there are some issues in relation to the way bibliometrix interprets the authors’ names. When two or more authors share the last name and the first letter of the first name, bibliometrix considers that it is the same author. For example, “Doe, John” is assumed to be the same author as “Doe, Jack”.
I’m sending a bibtex file, as an example.

PS: Rename the extension to example.bib and use scopus database in the analysis.

[example.bib.txt](https://github.com/massimoaria/bibliometrix/files/11027455/example.bib.txt)

**Comment by thimacek** [comment]
This seems to be one of a few problems related to author disambiguation. Sometimes your database will include different versions of the same author as well - say, "Doe, John August", "Doe, John A" and "Doe, John". If their first names are given in the database as "Doe JA", "Doe J A" and "Doe J", they may be recognised as different authors - and as you said, "Doe John" may be assumed to be the same author as "Doe, Jack".

This is a hard problem to deal with in general, because it's generally hard to deal with all cases that may come up AND avoid other problems. 

The way I've dealt with that for now was double-checking the input database to verify instances of a) the same author being referred to with different names (in the 'AU' and 'AF' field tags, although particularly 'AU' as that's the one bibliometrix uses to match authors); 
and b) different authors sharing the same first name(s) and last name. In that case, what I did was giving them singular codes (say, DOE, J1 and DOE, J2). It helps having an object (or an external document) with the dictionary of full name ('AF') and abbreviated names ('AU') so you can keep track of codes and key them properly.

This should solve the problem for productivity and coauthorship analysis, which use info on your database. It doesn't for citation analysis, though - and combing through all cited references to check this kind of thing is usually not viable.

I'm still trying to come up with something to deal with that - if the bibliometrix team has ideas, that'd be grand!

**Comment by a45285** [comment]
Thanks for replying,
I've been trying the solution proposed as well as some variations. For example, instead of Doe, J1 I tried Doe, 1J however the initial number is ignored. Doe, J1 and Doe, J2 is also considered the same author. So, the solution I've came up with was to use another letter unique for all authors, like Doe, A and Doe, B.

**Comment by a45285** [comment]
Waiting for this to be solved!
