### ISSUE TITLE
ERROR: co-occurrences network on abstract 

### ISSUE THREAD

**Issue by bboyewoon** [massimoaria/bibliometrix#341]
Hi, 
I want to analyze the centrality of abstracts, 

> NetMatrix = biblioNetwork(M,analysis = "co-occurrences", network = "abstracts", sep = ";")
> Error in '[.data.frame' (M, , Field): undefined columns selected 

i got error for this code.
scopus and WoS Both data files have the same error.

but 

> NetMatrix = biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";")

or any other biblioNetwork codes work.

i have bibliometrix version 4.1.3

full code :

> library(bibliometrix)
> file = 'scopus.bib'
> M = convert2df(file = file, dbsource = "scopus", format = "bibtex")
> NetMatrix = biblioNetwork(M,analysis = "co-occurrences", network = "abstracts", sep = ";")

WoS data file:
https://drive.google.com/file/d/1uRaAhheyouWTYGvF1_3Nu3_uws3JhQXy/view?usp=sharing

scopus data file:
https://drive.google.com/file/d/1p3p4bOhcKihjn6MkEkNZyl_X6vYCGDKG/view?usp=sharing

Thank you.

**Comment by massimoaria** [comment]
Hello,
you get an error in your code because you are trying to parse abstracts without first extracting individual words (ngrams=1) or sequences of words (ngrams=2, ...) from them.
The biblioAnalysis function needs an abstract field that has already been "tokenized."
To do this you must use the termExtraction() function, which will create a column called "AB_TM" in which the tokens extracted from the abstracts will be stored.

Here is an example code:

```
library(bibliometrix)

file = 'savedrecs.bib'

M = convert2df(file = file, dbsource = "wos", format = "bibtex")

M <-  termExtraction(M, Field="AB",   
                     ngrams = 1,
                     stemming = FALSE,
                     language = "english",
                     remove.numbers = TRUE,
                     remove.terms = NULL,
                     keep.terms = NULL,
                     synonyms = NULL,
                     verbose = TRUE)

NetMatrix = biblioNetwork(M, analysis = "co-occurrences", network = "abstracts", sep = ";")
```
