### ISSUE TITLE
Issue with Initial Visualization of Field Coverage

### ISSUE THREAD

**Issue by lemdark** [massimoaria/bibliometrix#383]
I hope this message finds you well. 

I'm reaching out regarding an inability to generate the initial viz with the coverage of the different fields for this [dataset](https://drive.google.com/file/d/15ZNfKwjdEHxF77qLlb7gqSFFdMQh2d1W/view). What can be the reason for this issue and how can it be resolved?

Thank you for your attention to this matter. 
Looking forward to your reply.

**Comment by massimoaria** [comment]
How did you create your dataset?

Bibliometrix/Biblioshiny only accepts files coming from one of the supported databases. 
The file .rdata you are trying to load appears to have been created by hand and not using the bibliometrix conversion routines.
That's why many metadata cannot be recognized.

For example, taking a look to your file, the column DE (authors' keywords) is completely empty!
