### ISSUE TITLE
biblioshiny does not export a Pajek file for network graphs

### ISSUE THREAD

**Issue by milliken** [massimoaria/bibliometrix#409]
I have been trying to export Pajek files for network analysis from Biblioshiny but on both Firefox and Chrome no file is downloaded.  This has worked previously, even a week ago, but stopped working after updating to Bibliometrix 4.1.4 (Win 10).

**Comment by milliken** [comment]
When I hit the Pajek button in the Biblioshiny menu for a network analysis, typically Firefox will open a new tab that is blank and nothing is downloaded and there is no error message.  If I try the same in Chrome, I get an error: "network.htm Failed - No file".

**Comment by milliken** [comment]
I'll add that I just installed Bibliometrix on my mac and everything worked fine. I then reinstalled Bibliometrix 4.1.4 on my Windows machine and it still gives the same results.

**Comment by massimoaria** [comment]
The issue is due to a problem with R's zipper() function with the Windows operating system. So when Biblioshiny attempts to compress files into a zipper archive, the function returns a path error. 

The problem is solved by using the zipper library, which is robust on all operating systems.

Please update bibliometrix from GitHub and try it:

`
install.packages("remotes")         
remotes::install_github("massimoaria/bibliometrix")
`

**Comment by milliken** [comment]
That worked!

Thanks for your help.
