### ISSUE TITLE
Can we define university coupling network?

### ISSUE THREAD

**Issue by zlfccnu** [massimoaria/bibliometrix#42]
the  `biblioNetwork` function only creates coupling networks list below:
- Manuscript coupling (analysis = "coupling", network = "references")
- Authors coupling (analysis = "coupling", network = "authors")
- Source coupling (analysis = "coupling", network = "sources")
- Country coupling (analysis = "coupling", network = "countries")
For me, it seems quite straight foward to create the university coupling network, why this is missing?

**Comment by massimoaria** [comment]
Because biblioNetwork implements only the most used networks. 
You can create any network type using the function cocMatrix that provides a documents per attributes matrix.

e.g.

DU <- cocMatrix(M, Field = "AU_UN", type = "sparse", sep = ";", binary=FALSE)

NetMatrix=Matrix::crossprod(DU,DU)

Now NetMatrix is an affiliation co-occurrences matrix while:
 
NetMatrix=Matrix::crossprod(t(DU),t(DU))

is a coupling university matrix.



Il 17/04/2019 10:25:47, zlfccnu <notifications@github.com> ha scritto:
the biblioNetwork function only creates coupling networks list below:
* Manuscript coupling (analysis = "coupling", network = "references")
* Authors coupling (analysis = "coupling", network = "authors")
* Source coupling (analysis = "coupling", network = "sources")
* Country coupling (analysis = "coupling", network = "countries")
For me, it seems quite straight foward to create the university coupling network, why this is missing?
