### ISSUE TITLE
Source co-citation issue.

### ISSUE THREAD

**Issue by silbia95** [massimoaria/bibliometrix#46]
Hi, 
I merged a Scopus and a WoS database thanks to the function mergeDbSources. I need to merge them in order to use a unique database in Biblioshiny.
Quite everything works, except the "most cited source". In this graph are reported both sources and authors. Probably an error in the merge of the database occurred, but I can't understand which database column it uses to generate the "most cited sources".

Here my database and the wrong graph
[Issue.xlsx](https://github.com/massimoaria/bibliometrix/files/3181275/Issue.xlsx)
![newplot (1)](https://user-images.githubusercontent.com/42000625/57755220-98d78300-76f0-11e9-981c-0f3023e6a577.png)

Thanks

**Comment by massimoaria** [comment]
Cited sources are extracted by CR column.
Wos and Scopus use a very different codify to store cited references in the bibliographic records (column CR). When you merge the two DBs, cited references become not more consistent. That's why no software allows to do it. 
We are working on a new matching function to match and convert references into an unique format.
It will be deployed in a short time.
