### ISSUE TITLE
pubmed connection error

### ISSUE THREAD

**Issue by damenta** [massimoaria/bibliometrix#49]
First of all, thanks for the very usefull bibliometrix package

Recently I have had troubles with the pubmed connection server using the pubmed2df function
When I try to download around more than 15 records the next error appear 
"HTTP status was 429 Too Many Requests", months before, I used the function to download around1000 records successfully.

Do you have any idea about the problem and how to solve it?

Thanks in advance

Dago

**Comment by adourian1** [comment]
Seconded.

**Comment by tzengji** [comment]
This problem occurs because the Cited function (belonging to RISmed) in the pubmed2df cannot correctly retrieve data from PubMed central.

You can copy the source code of pubmed2df, 
create a new function (e.g. pm2df) 
and change 
TC=Cited(records) 
to 
TC=rep(NA, length(Country(records))) 
or other good codes.

Tzeng-Ji Chen

**Comment by tzengji** [comment]
The problem of Cited function in RISmed is that it has sent too many requests in a given amount of time (HTTP status was '429 Too Many Requests'). 

You can copy the source code of Cited (in RISmed), 
create a new function (e.g. CitedNew) 
and add 
Sys.sleep(1) 
as the first line within the function(id).

And then modify the pubmed2df by changing 
TC=Cited(records)
to
TC=CitedNew(records) .

Tzeng-Ji Chen

**Comment by massimoaria** [comment]
Solved. Bibliometrix 3.0 includes direct support to pubmed API through the package pubmedR.
