### ISSUE TITLE
Is it possible to replace the "M" matrix?

### ISSUE THREAD

**Issue by lucdri** [massimoaria/bibliometrix#60]
Dear Professor Massimo,

The AU_UN column of matrix M does not have all affiliations of the authors. I looked in the Bibtex file (Web of Science) and I realized that when two or more authors have the same affiliation, only one institution is counted. So I decided to modify the M matrix in Excel by inserting the missing institutions.

I saved the "M" matrix as csv and modified the AU_UN column by inserting new affiliations. Then I saved it in csv format and tried uploading the file from this statement:

> D <- readFiles ("Pasta5_TESTE.csv")
> M <- convert2df (D, dbsource = "isi", format = "csv")

Converting your isi collection into a bibliographic dataframe

 'format' argument is not properly specified
 'format' argument has to be a character string matching 'plaintext' or 'bibtex'.
Error in "PY"% in% names (M): object 'M' not found

Did not work. Is it possible to modify the matrix M and continue using the bibliometrix? Is there another way to do this?

Thank you very much.

**Comment by massimoaria** [comment]
You have two possible ways:
1) Use original C1 instead of AU_UN (disambiguated affiliations)

2) 
a) export M in excel using the rio package
rio::export(M,file="M.xlsx")

b) modify the column AU_UN

c) import the excel file in R
rio::import("M.xlsx")
row.names(M)=M$SR

now, modified M should work with bibliometrix
