### ISSUE TITLE
What does "NR" mean?

### ISSUE THREAD

**Issue by frajuegies** [massimoaria/bibliometrix#7]
Dear all,
I just discovered your package... thank you very much for your work. It's great!
For my first steps I have used the attached bib-file (zipped for Github) downloaded from Web of Science.

Using 
```
library (bibliometrix)
D <- readFiles("C:/Users/u991726/Downloads/savedrecs (3).bib")
M <- convert2df(D, dbsource = "isi", format = "bibtex")
results <- biblioAnalysis(M, sep = ";")

```
results$Affiliation delivers 628 "NR".... So many of the affiliation were not parsed correctly(?). 

Did I missed something?

Best regards and thank you very much !

Juergen

[savedrecs (3).zip](https://github.com/massimoaria/bibliometrix/files/1720401/savedrecs.3.zip)

**Comment by massimoaria** [comment]
Dear Juergen,

the issue is due to the not standardized format of affiliation in bibtex isi format.
For example in this file, affiliation field contains also the author's names so became almost impossible to work with raw data.
The function metaTagExtraction (recalled by biblioAnalysis) tries to identify affiliations matching terms from a preset dictionary (i.e. "UNIV", "LAB", "CENTER", etc.). When an author works in a private firm (i.e Toyota in this collection), the affiliation is not recognized.
Looking at this collection, I have just extended the dictionary with more terms.  Now the NR are just 305. This number is not too big considering that in this collection there are 2827 authors.
If you want extract raw affiliations, you can use tableTag function:
Aff <- tableTag(M, Tag = "C1", sep = ";")

Please install the updated version of bibliometrix.

**Comment by frajuegies** [comment]
Thank you very much for your explanation.... I assume the updated version is not on CRAN yet.....

The approach with tableTag seems to be very interesting as I am looking for links between companies and research institutes.

Best regards, Jürgen
