### ISSUE TITLE
`non-character argument` error when trying to plot a historiograph 

### ISSUE THREAD

**Issue by charles-plessy** [massimoaria/bibliometrix#70]
Hello, I am using the `biblioshiny` app from `bibliometrix 2.2.1`, but I am not able to plot a historiograph using data downloaded from the _Web of Science_ in _Plain Text_ format using the _Full Record and Cited References_: I always get a `non-character argument` error. Some other graphs can be produced without problems, for instance the _Authors' Production over Time_. Data from the `joi.zip` example works fine, and with casual inspection of the contents, I do not see a clear difference (except for the presence of a byte order mark, but removing it does not solve my problem).  Am I doing something wrong with the data preparation ?

**Comment by massimoaria** [comment]
Please, send me your zip file

**Comment by massimoaria** [comment]
The error is due to a too small set of articles that does not match the function arguments.
For example, "Number of Nodes" means the number of articles to include in the analysis (with a min. number of citation = 1).  Default is 20 but you have only 3 documents in your collection and one of these has 0 citations!
Setting "Number of Nodes" equals to 10 all work well.
Please, try it.
![image](https://user-images.githubusercontent.com/16023543/63844315-43b23b00-c988-11e9-8265-0117cd11ea56.png)

[bibliometrix.zip](https://github.com/massimoaria/bibliometrix/files/3550170/bibliometrix.zip)
.

I downloaded a bibliographic collection composed by the bibliometrix article (published on JoI, 2017)  and all documents that cited it (37 articles).

**Comment by charles-plessy** [comment]
Thanks, it works with the `bibliometrix.zip` that you supplied above. If possible, I would be pleased if the error message would directly report that the number of articles is too low for the selected parameters.

**Comment by charles-plessy** [comment]
Alternatively, would it be possible to plot a non-connected dot for papers that are not cited nor citing any other ?  I would find it useful when plotting my bibliography.
