### ISSUE TITLE
"Plaintext" does not work in my example

### ISSUE THREAD

**Issue by frajuegies** [massimoaria/bibliometrix#8]
Hi,

using the attached WOS plaintext file and the following code

```
library (bibliometrix)
D <- readFiles("C:/Users/u991726/Downloads/savedrecs (1).txt")
M <- convert2df(D, dbsource = "isi", format = "plaintext")


```

an error is thrown:

Articles extracted   100 
Articles extracted   200 
Articles extracted   300 
Articles extracted   400 
Articles extracted   499 
Error in `$<-.data.frame`(`*tmp*`, "TC", value = numeric(0)) : 
  replacement has 0 rows, data has 499

Do you know the reason for this error?

Best regards,
Jürgen
[savedrecs (1).zip](https://github.com/massimoaria/bibliometrix/files/1723494/savedrecs.1.zip)

**Comment by frajuegies** [comment]
One add-on:
Using:

```
D <- readFiles("C:/Users/u991726/Downloads/savedrecs (1).txt")
M1 <- isi2df(D)

```
delivers a dataframe but does not include a "C1" column.

Best regards,
Jürgen

**Comment by massimoaria** [comment]
This is not an issue of bibliometrix.
In your file savedrecs, information about Total Citation (TC) and Affiliation (C1) are missing because you did not select "all the available data about marked records" when downloading the file.
This procedure is illustrated in the bibliometrix vignette (see the attached screenshot). 
![download](https://user-images.githubusercontent.com/16023543/36213851-144d98e4-11a8-11e8-84c2-e8448741867b.png)

**Comment by frajuegies** [comment]
You are totally right... I just discovered my error.

Sorry for that....
And.. you are right with respect to the info in C1; it should more easy to split the info in authors and affiliation using plaintext...

Thank you very much
Jürgen
